datadog:
  site: datadoghq.com
  # Secret created by ExternalSecret datadog-api-key (gitops/secret-stores/).
  # Vault path: secret/datadog/api → keys: key (api), app (app key).
  apiKeyExistingSecret: datadog
  appKeyExistingSecret: datadog
  logs:
    enabled: true
    containerCollectAll: true
  apm:
    enabled: true
  processAgent:
    enabled: true
  kubelet:
    tlsVerify: false

clusterAgent:
  enabled: true
  metricsProvider:
    enabled: true
  podAnnotations:
    consul.hashicorp.com/connect-inject: "false"
    linkerd.io/inject: disabled

agents:
  podAnnotations:
    consul.hashicorp.com/connect-inject: "false"
    linkerd.io/inject: disabled

clusterChecksRunner:
  podAnnotations:
    consul.hashicorp.com/connect-inject: "false"
    linkerd.io/inject: disabled
