apiVersion: v1
kind: ServiceAccount
metadata:
  name: payments-app
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "payments-app.labels" . | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: payments-processor
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "payments-app.labels" . | nindent 4 }}
