meshProvider: gatewayapi:v1beta1
metricsServer: http://prometheus.linkerd-viz:9090

podAnnotations:
  consul.hashicorp.com/connect-inject: "false"
  linkerd.io/inject: enabled

podMonitor:
  enabled: false

prometheus:
  install: false

slack:
  url: ""
  channel: ""
