namespace: payments-app

mesh: linkerd
secrets: vault

paymentsApp:
  image: hashicorpdemoapp/payments:latest
  replicas: 2

paymentsProcessor:
  image: hashicorpdemoapp/payments:latest
  replicas: 1

publicApi:
  image: hashicorpdemoapp/public-api:latest
  replicas: 1

frontend:
  image: hashicorpdemoapp/frontend-nginx:latest
  replicas: 1

ingress:
  host: gateway.hashiconf.example.com

vault:
  address: "http://vault.vault.svc.cluster.local:8200"

sops: {}
