namespace: payments-app

mesh: linkerd
secrets: vault

paymentsApp:
  image: hashicorpdemoapp/payments:v0.0.16
  replicas: 1

paymentsProcessor:
  image: hashicorpdemoapp/payments:v0.0.16
  replicas: 1

publicApi:
  image: hashicorpdemoapp/public-api:v0.0.7
  replicas: 1

productApi:
  image: hashicorpdemoapp/product-api:v0.0.20
  replicas: 1

productDb:
  image: hashicorpdemoapp/product-api-db:v0.0.20
  replicas: 1
  database: products
  username: postgres
  password: password

frontend:
  image: hashicorpdemoapp/frontend-nginx:v1.0.9
  replicas: 1
  publicApiUrl: "/"
  footerFlag: "HashiCups"

ingress:
  host: gateway.hashiconf.example.com

vault:
  address: "http://vault.vault.svc.cluster.local:8200"

db:
  host: "terragrunt-infra-payments.cngggs0q8d4s.ap-southeast-1.rds.amazonaws.com"

sops: {}
