apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linkerd-viz-policy
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: platform
  source:
    repoURL: https://github.com/dungxtd/terragrunt-stacks
    targetRevision: main
    path: gitops/platform/linkerd-viz-policy
  destination:
    server: https://kubernetes.default.svc
    namespace: linkerd-viz
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
