apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: payments-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: platform
  sources:
    - repoURL: https://github.com/dungxtd/terragrunt-stacks
      targetRevision: main
      path: gitops/charts/payments-app
      helm:
        valueFiles:
          - $values/gitops/values/payments-app/production.yaml
    - repoURL: https://github.com/dungxtd/terragrunt-stacks
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: payments-app
  ignoreDifferences:
    - group: apps
      kind: Deployment
      name: payments-app
      jsonPointers:
        - /spec/replicas
    - group: argoproj.io
      kind: Rollout
      name: payments-app
      jsonPointers:
        - /spec/replicas         # Rollouts scales itself during canary
    - group: ""
      kind: Service
      name: payments-app
      jsonPointers:
        - /spec/selector         # Rollouts patches selector with rollouts-pod-template-hash
    - group: ""
      kind: Service
      name: payments-app-canary
      jsonPointers:
        - /spec/selector
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: payments-app
      jsonPointers:
        - /spec/rules         # gateway-api plugin patches backendRefs[*].weight
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
