apiVersion: v1
kind: Service
metadata:
  name: payments-app
  namespace: {{ .Values.namespace }}
  labels:
    app: payments-app
    {{- include "payments-app.labels" . | nindent 4 }}
spec:
  selector:
    app: payments-app
  ports:
    - port: 8080
      targetPort: 8080
      name: http
  type: ClusterIP
