apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-processor
  namespace: {{ .Values.namespace }}
  labels:
    app: payments-processor
    {{- include "payments-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.paymentsProcessor.replicas }}
  selector:
    matchLabels:
      app: payments-processor
  template:
    metadata:
      labels:
        app: payments-processor
      annotations:
        {{- if eq .Values.mesh "linkerd" }}
        linkerd.io/inject: enabled
        {{- end }}
        {{- if eq .Values.mesh "consul" }}
        consul.hashicorp.com/connect-inject: "true"
        {{- else }}
        consul.hashicorp.com/connect-inject: "false"
        {{- end }}
    spec:
      serviceAccountName: payments-processor
      containers:
        - name: payments-processor
          image: {{ .Values.paymentsProcessor.image }}
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: NAME
              value: "payments-processor"
            {{- if eq .Values.secrets "vault" }}
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: payments-processor-creds
                  key: password
            {{- end }}
            {{- if eq .Values.secrets "sops" }}
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: payments-processor-creds
                  key: password
            {{- end }}
          resources:
            requests:
              cpu: 100m
              memory: 384Mi
            limits:
              cpu: 500m
              memory: 768Mi
