apiVersion: v1
kind: Service
metadata:
  name: payments-processor
  namespace: {{ .Values.namespace }}
  labels:
    app: payments-processor
    {{- include "payments-app.labels" . | nindent 4 }}
spec:
  selector:
    app: payments-processor
  ports:
    - port: 9090
      targetPort: 8080
      name: http
  type: ClusterIP
