apiVersion: v1
kind: Service
metadata:
  name: product-db
  namespace: {{ .Values.namespace }}
  labels:
    app: product-db
    {{- include "payments-app.labels" . | nindent 4 }}
spec:
  selector:
    app: product-db
  ports:
    - port: 5432
      targetPort: 5432
      name: postgres
  type: ClusterIP
