apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-db
  namespace: {{ .Values.namespace }}
  labels:
    app: product-db
    {{- include "payments-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.productDb.replicas }}
  selector:
    matchLabels:
      app: product-db
  template:
    metadata:
      labels:
        app: product-db
    spec:
      containers:
        - name: product-db
          image: {{ .Values.productDb.image }}
          ports:
            - containerPort: 5432
              name: postgres
          env:
            - name: POSTGRES_DB
              value: {{ .Values.productDb.database | quote }}
            - name: POSTGRES_USER
              value: {{ .Values.productDb.username | quote }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.productDb.password | quote }}
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
