apiVersion: v1
kind: Service
metadata:
  name: product-api
  namespace: {{ .Values.namespace }}
  labels:
    app: product-api
    {{- include "payments-app.labels" . | nindent 4 }}
spec:
  selector:
    app: product-api
  ports:
    - port: 9090
      targetPort: 9090
      name: http
  type: ClusterIP
