{{- if eq .Values.secrets "vault" }}
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultConnection
metadata:
  name: default
  namespace: {{ .Values.namespace }}
spec:
  address: {{ .Values.vault.address | quote }}
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: payments-app
  namespace: {{ .Values.namespace }}
spec:
  vaultConnectionRef: default
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: payments
    serviceAccount: payments-app
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: payments-processor
  namespace: {{ .Values.namespace }}
spec:
  vaultConnectionRef: default
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: payments-processor
    serviceAccount: payments-processor
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: payments-processor-creds
  namespace: {{ .Values.namespace }}
spec:
  type: kv-v2
  mount: payments-processor/static
  path: creds
  destination:
    name: payments-processor-creds
    create: true
  refreshAfter: 30s
  vaultAuthRef: payments-processor
{{- end }}
{{- if eq .Values.secrets "sops" }}
apiVersion: v1
kind: Secret
metadata:
  name: payments-app-db-creds
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "payments-app.labels" . | nindent 4 }}
type: Opaque
stringData:
  connection_string: {{ .Values.sops.dbConnectionString | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: payments-processor-creds
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "payments-app.labels" . | nindent 4 }}
type: Opaque
stringData:
  password: {{ .Values.sops.processorPassword | quote }}
{{- end }}
