namespace: payments-app

mesh: linkerd
secrets: sops

paymentsApp:
  image: hashicorpdemoapp/payments:v0.0.16
  replicas: 2

paymentsProcessor:
  image: hashicorpdemoapp/payments:v0.0.16
  replicas: 1

ingress:
  host: payments.example.com
  certificateArn: "arn:aws:acm:ap-southeast-1:ACCOUNT:certificate/CERT_ID"

sops:
  dbConnectionString: "ENC[AES256_GCM,data:...,type:str]"
  processorPassword: "ENC[AES256_GCM,data:...,type:str]"

vault: {}
